@startuml Main
'https://plantuml.com/class-diagram

class Game

class Actor {
    +update(float stepTime)
    +render(RenderTarget* target)
    +addComponent(IComponent* component)
    +removeComponent(IComponent* component)
    -deque<IComponent*> mComponents
}

class IComponent {
    {abstract}+update(float stepTime)
    {abstract}+render(RenderTarget* target)
}

class Component {
    {abstract}+update(float stepTime)
    {abstract}+render(RenderTarget* target)
}

class Sprite {
    {abstract}+update(float stepTime)
    {abstract}+render(RenderTarget* target)
}

class Animation {
    {abstract}+update(float stepTime)
    {abstract}+render(RenderTarget* target)
}

class Background {
    {abstract}+update(float stepTime)
    {abstract}+render(RenderTarget* target)
}

Game "1" *-- "0..*" Actor

Actor "1" *-- "0..*" IComponent

IComponent <|-- Component
Component <|-- Sprite

Sprite <|-- Animation
Sprite <|-- Background

@enduml
